name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Check License
        run: mvn  license:check

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Build
        run: mvn clean package

